"""
Классификация продуктов по категориям — статический словарь без запросов к AI.
Покрывает ~90% типичных продуктов русскоязычного рациона.
"""

# Категории и их русские названия
CATEGORIES = {
    "meat_fish":      "Мясо и рыба",
    "dairy":          "Молочка и яйца",
    "vegetables":     "Овощи",
    "fruits":         "Фрукты",
    "grains":         "Крупы и хлеб",
    "fats_sauces":    "Масла и соусы",
    "other":          "Прочее",
}

# Ключевые слова → категория. Порядок важен: проверяем сверху вниз, первое совпадение побеждает.
_KEYWORDS: list[tuple[str, str]] = [
    # Мясо и рыба
    ("курин",        "meat_fish"),
    ("грудк",        "meat_fish"),
    ("бедр",         "meat_fish"),
    ("филе",         "meat_fish"),
    ("свинин",       "meat_fish"),
    ("говядин",      "meat_fish"),
    ("телятин",      "meat_fish"),
    ("баранин",      "meat_fish"),
    ("индейк",       "meat_fish"),
    ("уткa",         "meat_fish"),
    ("кролик",       "meat_fish"),
    ("фарш",         "meat_fish"),
    ("сосиск",       "meat_fish"),
    ("сардельк",     "meat_fish"),
    ("колбас",       "meat_fish"),
    ("ветчин",       "meat_fish"),
    ("бекон",        "meat_fish"),
    ("карбонад",     "meat_fish"),
    ("шейк",         "meat_fish"),
    ("окорок",       "meat_fish"),
    ("стейк",        "meat_fish"),
    ("котлет",       "meat_fish"),
    ("рыб",          "meat_fish"),
    ("лосос",        "meat_fish"),
    ("форел",        "meat_fish"),
    ("сёмг",         "meat_fish"),
    ("семг",         "meat_fish"),
    ("тунец",        "meat_fish"),
    ("треск",        "meat_fish"),
    ("минтай",       "meat_fish"),
    ("хек",          "meat_fish"),
    ("судак",        "meat_fish"),
    ("окун",         "meat_fish"),
    ("карп",         "meat_fish"),
    ("скумбри",      "meat_fish"),
    ("сельд",        "meat_fish"),
    ("горбуш",       "meat_fish"),
    ("кета",         "meat_fish"),
    ("морепродукт",  "meat_fish"),
    ("креветк",      "meat_fish"),
    ("кальмар",      "meat_fish"),
    ("краб",         "meat_fish"),
    ("мидий",        "meat_fish"),
    ("икра",         "meat_fish"),
    ("печен",        "meat_fish"),
    ("субпродукт",   "meat_fish"),
    ("сердц",        "meat_fish"),
    ("язык",         "meat_fish"),

    # Растительные масла — ДО молочки
    ("масло растит",    "fats_sauces"),
    ("масло подсолн",   "fats_sauces"),
    ("масло оливк",     "fats_sauces"),
    ("масло кокос",     "fats_sauces"),
    ("масло льнян",     "fats_sauces"),
    ("оливков масл",    "fats_sauces"),
    ("подсолнечн масл", "fats_sauces"),

    # Молочка и яйца
    ("яйц",          "dairy"),
    ("яйко",         "dairy"),
    ("молок",        "dairy"),
    ("кефир",        "dairy"),
    ("ряженк",       "dairy"),
    ("йогурт",       "dairy"),
    ("сметан",       "dairy"),
    ("творог",       "dairy"),
    ("сыр",          "dairy"),
    ("масл",         "dairy"),   # сливочное масло — растительные уже отловлены выше
    ("сливк",        "dairy"),
    ("простоквашк",  "dairy"),
    ("ацидофилин",   "dairy"),
    ("айран",        "dairy"),
    ("мацони",       "dairy"),
    ("пармезан",     "dairy"),
    ("моцарелл",     "dairy"),
    ("рикотт",       "dairy"),
    ("брынз",        "dairy"),
    ("фет",          "dairy"),
    ("пломбир",      "dairy"),

    # Овощи
    ("овощ",         "vegetables"),   # «овощи», «овощная смесь»
    ("картофел",     "vegetables"),
    ("картошк",      "vegetables"),
    ("морков",       "vegetables"),
    ("лук",          "vegetables"),
    ("чеснок",       "vegetables"),
    ("капуст",       "vegetables"),
    ("брокколи",     "vegetables"),
    ("цветн",        "vegetables"),
    ("помидор",      "vegetables"),
    ("томат",        "vegetables"),
    ("огурец",       "vegetables"),
    ("огурц",        "vegetables"),
    ("перец",        "vegetables"),
    ("баклажан",     "vegetables"),
    ("кабачок",      "vegetables"),
    ("тыкв",         "vegetables"),
    ("свёкл",        "vegetables"),
    ("свекл",        "vegetables"),
    ("редис",        "vegetables"),
    ("редьк",        "vegetables"),
    ("шпинат",       "vegetables"),
    ("салат",        "vegetables"),
    ("руккол",       "vegetables"),
    ("зелен",        "vegetables"),
    ("укроп",        "vegetables"),
    ("петрушк",      "vegetables"),
    ("кинза",        "vegetables"),
    ("базилик",      "vegetables"),
    ("сельдерей",    "vegetables"),
    ("спаржа",       "vegetables"),
    ("артишок",      "vegetables"),
    ("горошек",      "vegetables"),
    ("кукуруз",      "vegetables"),
    ("фасол",        "vegetables"),
    ("чечевиц",      "vegetables"),
    ("нут",          "vegetables"),
    ("соя",          "vegetables"),
    ("грибы",        "vegetables"),
    ("гриб",         "vegetables"),
    ("шампиньон",    "vegetables"),
    ("вешенк",       "vegetables"),
    ("белый гриб",   "vegetables"),
    ("порей",        "vegetables"),
    ("пастернак",    "vegetables"),

    # Фрукты
    ("ягод",         "fruits"),       # «ягоды», «ягодная смесь»
    ("фрукт",        "fruits"),
    ("яблок",        "fruits"),
    ("груш",         "fruits"),
    ("банан",        "fruits"),
    ("апельсин",     "fruits"),
    ("мандарин",     "fruits"),
    ("лимон",        "fruits"),
    ("грейпфрут",    "fruits"),
    ("слив",         "fruits"),
    ("персик",       "fruits"),
    ("абрикос",      "fruits"),
    ("вишн",         "fruits"),
    ("черешн",       "fruits"),
    ("виноград",     "fruits"),
    ("клубник",      "fruits"),
    ("малин",        "fruits"),
    ("черник",       "fruits"),
    ("смородин",     "fruits"),
    ("крыжовник",    "fruits"),
    ("арбуз",        "fruits"),
    ("дын",          "fruits"),
    ("киви",         "fruits"),
    ("манго",        "fruits"),
    ("ананас",       "fruits"),
    ("хурм",         "fruits"),
    ("гранат",       "fruits"),
    ("инжир",        "fruits"),
    ("финик",        "fruits"),
    ("изюм",         "fruits"),
    ("чернослив",    "fruits"),
    ("курага",       "fruits"),
    ("сухофрукт",    "fruits"),

    # Крупы и хлеб
    ("гречк",        "grains"),
    ("рис",          "grains"),
    ("овсянк",       "grains"),
    ("овёс",         "grains"),
    ("овес",         "grains"),
    ("геркулес",     "grains"),
    ("пшен",         "grains"),
    ("перловк",      "grains"),
    ("манк",         "grains"),
    ("булгур",       "grains"),
    ("киноа",        "grains"),
    ("кускус",       "grains"),
    ("полент",       "grains"),
    ("кукурузн крупа", "grains"),
    ("макарон",      "grains"),
    ("паст",         "grains"),
    ("спагетт",      "grains"),
    ("лапш",         "grains"),
    ("вермишел",     "grains"),
    ("хлеб",         "grains"),
    ("батон",        "grains"),
    ("буханк",       "grains"),
    ("булочк",       "grains"),
    ("лаваш",        "grains"),
    ("питa",         "grains"),
    ("тортилья",     "grains"),
    ("мука",         "grains"),
    ("крахмал",      "grains"),
    ("хлопья",       "grains"),
    ("мюсли",        "grains"),
    ("гранол",       "grains"),
    ("сухар",        "grains"),
    ("хлебец",       "grains"),

    # Масла растительные — до молочного «масло сливочное»
    ("масло растит",   "fats_sauces"),
    ("масло подсолн",  "fats_sauces"),
    ("масло оливк",    "fats_sauces"),
    ("масло кокос",    "fats_sauces"),
    ("масло льнян",    "fats_sauces"),
    ("масло кунжут",   "fats_sauces"),
    ("масло горчич",   "fats_sauces"),
    ("оливков масл",   "fats_sauces"),
    ("подсолнечн масл","fats_sauces"),
    ("майонез",      "fats_sauces"),
    ("кетчуп",       "fats_sauces"),
    ("соус",         "fats_sauces"),
    ("горчиц",       "fats_sauces"),
    ("уксус",        "fats_sauces"),
    ("соевый соус",  "fats_sauces"),
    ("аджик",        "fats_sauces"),
    ("сальс",        "fats_sauces"),
    ("песто",        "fats_sauces"),
    ("тхин",         "fats_sauces"),
    ("паста томатн", "fats_sauces"),
    ("томатн паст",  "fats_sauces"),
    ("орех",         "fats_sauces"),
    ("миндал",       "fats_sauces"),
    ("кешью",        "fats_sauces"),
    ("грецкий",      "fats_sauces"),
    ("арахис",       "fats_sauces"),
    ("семечк",       "fats_sauces"),
    ("семена",       "fats_sauces"),
    ("льняные",      "fats_sauces"),
    ("чиа",          "fats_sauces"),
    ("авокадо",      "fats_sauces"),
    ("шоколад",      "fats_sauces"),
    ("какао",        "fats_sauces"),
    ("кофе",         "fats_sauces"),
    ("чай",          "fats_sauces"),
    ("специ",        "fats_sauces"),
    ("приправ",      "fats_sauces"),
    ("соль",         "fats_sauces"),
    ("сахар",        "fats_sauces"),
    ("мёд",          "fats_sauces"),
    ("мед",          "fats_sauces"),
    ("варенье",      "fats_sauces"),
    ("джем",         "fats_sauces"),
    ("протеин",      "fats_sauces"),
    ("батончик",     "fats_sauces"),
]


def classify_product(name: str) -> str:
    """
    Возвращает ключ категории для продукта по его названию.
    Всегда возвращает валидный ключ из CATEGORIES.
    """
    if not name:
        return "other"
    normalized = name.strip().lower()
    for keyword, category in _KEYWORDS:
        if keyword in normalized:
            return category
    return "other"


def classify_product_display(name: str) -> str:
    """Возвращает читаемое название категории на русском."""
    return CATEGORIES.get(classify_product(name), CATEGORIES["other"])